name: Test

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:

env:
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: 'true'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache

    - name: Build
      run: |
        npm install
        npm run build
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    #- name: Upload to artifact
    #  uses: actions/upload-artifact@main
    #  with:
    #    name: build-${{ env.FILE_DATE }}.zip
    #    path: public
